wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.31
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.5
    t:
      1:
      - 1
      - 9
      4: 3.8.5
      5: 0.10.31
      8:
      - 2
      - 3
      - 5
